version: '3.9'
services:
  db:
    image: postgres:14.3-alpine
    restart: always
    env_file:
      - config/docker.env
    ports:
      - '5432:5432'
    volumes:
      - db:/var/lib/postgresql/data
      - ./docker/create-db.sql:/docker-entrypoint-initdb.d/create-db.sql
  setup:
    depends_on:
      - db
    build:
      dockerfile: docker/Dockerfile
      context: .
      target: development
    command:
      - ./manage.py
      - migrate
    env_file:
      - config/docker.env
    volumes:
      - .:/app
  app:
    depends_on:
      - db
      - setup
    build:
      dockerfile: docker/Dockerfile
      context: .
      target: development
    command:
      - ./manage.py
      - runserver
      - 0.0.0.0:80
    env_file:
      - config/docker.env
    volumes:
      - .:/app
    ports:
      - '8000:80'
volumes:
  db:
    driver: local