# Generated by Django 4.0.4 on 2022-06-01 12:55

import uuid

import django.db.models.deletion
import django_countries.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Address",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[("M", "Mailing address"), ("B", "Billing address")],
                        db_index=True,
                        max_length=1,
                    ),
                ),
                ("full_name", models.CharField(max_length=120)),
                ("line_1", models.CharField(max_length=120)),
                ("line_2", models.CharField(blank=True, max_length=60, null=True)),
                ("line_3", models.CharField(blank=True, max_length=60, null=True)),
                ("city", models.CharField(max_length=100)),
                ("county", models.CharField(blank=True, max_length=50)),
                ("district", models.CharField(blank=True, max_length=50)),
                ("state_or_region", models.CharField(max_length=50)),
                ("postal_code", models.CharField(max_length=20)),
                ("country", django_countries.fields.CountryField(max_length=2)),
                ("phone", models.CharField(max_length=20)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "addresses",
                "unique_together": {
                    ("user", "full_name", "line_1", "city", "postal_code", "country")
                },
            },
        ),
    ]
